### PR TITLE
Implement API

### PR DESCRIPTION
**Pull request by julkue**

### CODE REVIEW

**Comment by julkue** [comment]
@Mottie Could you review [this PR](https://github.com/diacritics/api/pull/1/files)? As soon as https://github.com/diacritics/database/pull/9 is merged I just need to update the link to the diacritics.json again and I think I'm done.

For reviewing the responses I can recommend you to use the latest FF Dev as it shows the JSON response in a beautiful way:

**Comment by julkue** [comment]
@Mottie When will you have time to review this? No stress, I'd just like to calculate when I can continue.

**Comment by Mottie** [comment]
Notes:

* After testing `/?variant=Austria`, I think it might be nice to allow using the two letter code to get the same data (i.e. `/?variant=at`).
* Since `de` is on the same level as `at` in the database, maybe using `/?variant=de` should return the root language data, and not any of the other variants.

I do think we need to address the naming of the variant files. The ISO 639-1 list only includes the root language. Variants are covered by the IETF language tags ([ref](http://data.okfn.org/data/core/language-codes)). This would require a few changes to the spec, but it isn't overly difficult.

Everything else that I tested appears to work great! Nice work! 👍

**Comment by julkue** [comment]
I agree with both points. Once we allow specifying `at` as the variant, it's also possible to specify `de`. Therefore the second point is automatically done too.

Are this all findings, also grammar things (spec)? I expected more  :bowtie:

**Comment by Mottie** [comment]
I think we need more data... and I'm adding some more comments to the Concept & Specification issue... but they are related to the API.

**Comment by julkue** [comment]
@Mottie I've enhanced the `variant` filter with your suggestions. Could you please finally review this PR?

**Comment by julkue** [comment]
I'm going to implement further filter properties – e.g. to ignore some equivalents – later. This PR just includes the basics.

**Review by Mottie — APPROVED** [review]
LGTM! Nice work!

**Comment by julkue** [comment]
@Mottie Could you please review the recent changes? I've now replaced the route `/` with `/v1/` to make sure a specific version of the database is always defined. Internally, we have the basic `DatabaseFilter` class that will always contain the logic for the latest version and one or multiple versioned `DatabaseFilter` classes, e.g. `DatabaseFilterV1` (note **V1**).

In the current case `DatabaseFilter` and `DatabaseFilterV1` are equivalent, as we only have one version. So the `DatabaseFilterV1` class fully extends the `DatabaseFilter` class. Once a new version is coming the `DatabaseFilterV1` class would contain the old methods to retrieve data of `v1`, while `DatabaseFilter` would contain the latest logic.

I'm especially asking for review because I'm not sure if the spec describes this understandable. In case you can describe this better I'd appreciate if you'd directly commit it to `initial`.

**Comment by Mottie** [comment]
Everything looks like it is working great!

I just have a few more comments:

* Is doesn't seem possible to filter multiple values. For example, if I wanted the continent data for `NA` and `EU`:

    ```
    /v1/?continent=NA&EU
    // result: "Invalid filter parameter 'EU'"
    ```

    This would be nice to include for both the metadata and data filter parameters.

* Should we include a filter for native? (e.g. `/v1/?native=Deutsch`)

**Comment by julkue** [comment]
@Mottie Thanks for your reply!

> Is doesn't seem possible to filter multiple values. For example, if I wanted the continent data for NA and EU

You're right, it's currently only possible to search for one value. In case of `continent` it makes sense to search for multiple. I'll implement an option to specify them divided by a `,`, as `&` would be a separate filter. Because two different results may have to be formed (nothing trivial) I'm going to implement this later. I've created a card to keep track of this feature: https://github.com/diacritics/api/projects/1#card-919969

> Should we include a filter for native? 

Why do you think this is necessary? You can just use `/?language=Deutsch` and it works, as the language filter searches for the language code, the language written native or written in English.

**Comment by Mottie** [comment]
> & would be a separate filter

Ahh, you're right!

> You can just use `/?language=Deutsch`

Oh, you're right again! I missed that last bullet point in the spec.

**Comment by julmot** [comment]
@Mottie Yeay, we now have the basic API running on [Heroku](https://diacritics-api.herokuapp.com/v1/). I'm now spending some time customizing the domain.

**Comment by julkue** [comment]
@Mottie Yay, we now have our basic API running on [Heroku](https://diacritics.herokuapp.com/v1/). I'll now spend some time customizing the domain.

**Pull request merged**
